version: '3'

services:
  genealogy-server:
    build: ./provisioning
    image: modulargenealogy
    depends_on:
      - mysql
      - neo4j
    volumes:
      - ./:/application:cached

  mysql:
    image: mysql:5.7@sha256:c23e9bfe66eeffc990cf6bce4bb0e9c5c85eb908170f3b3dde3e9a12c5a91689
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=homestead
    volumes:
      - ./storage/tmp/db:/var/lib/mysql:cached

  nginx:
    image: nginx:latest@sha256:31b8e90a349d1fce7621f5a5a08e4fc519b634f7d3feb09d53fac9b12aa4d991
    ports:
      - "80:80"
    volumes:
      - ./provisioning/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
    depends_on:
      - genealogy-server

  neo4j:
    image: neo4j:latest@sha256:4c73bd0824a3596dbd7e9e9b70163a8c73447443a76bc845682b7071c98b7a28
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./db/dbms:/data/dbms
